/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/communes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Autocomplétion par nom, insensible aux accents et à la casse.
         *
         *     Matche en préfixe ou en milieu de nom sur `nom_recherche` (normalisé comme
         *     la saisie : « nim » → Nîmes, « denis » → Saint-Denis) ; les préfixes sortent
         *     en premier. Chaque résultat porte la couleur de synthèse (pastille) et la
         *     famille dominante quand elles existent, selon l'`algo` demandé.
         */
        get: operations["search_communes_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communes/proximite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proximite
         * @description Communes dont la géométrie est à moins de `rayon_m` mètres du point.
         */
        get: operations["proximite_communes_proximite_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communes/{insee}/couleur": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Couleur
         * @description Couleur synthétique OKLCH + participation d'une commune.
         */
        get: operations["couleur_communes__insee__couleur_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communes/{insee}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fiche
         * @description Fiche complète : métadonnées de la commune + couleur synthétique.
         */
        get: operations["fiche_communes__insee__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communes/{insee}/scrutins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste Scrutins
         * @description Liste des scrutins inclus dans la synthèse de la commune avec leur poids relatif.
         *
         *     Source : couleurs_ville.scrutins_inclus (JSON, liste de paires [type, poids_relatif])
         *     jointe à la table scrutins (id, type, date) pour la date.
         */
        get: operations["liste_scrutins_communes__insee__scrutins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communes/{insee}/scrutins/{scrutin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Scrutin
         * @description Détail d'un scrutin pour la commune :
         *     - Répartition par famille politique (voix et pourcentage des exprimés)
         *     - Participation
         *     - Couleur du scrutin (l, c, h depuis couleurs_scrutin)
         */
        get: operations["detail_scrutin_communes__insee__scrutins__scrutin_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Sonde de vivacité.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CommuneFiche
         * @description Fiche complète : métadonnées + couleur synthétique.
         */
        CommuneFiche: {
            /** Code Insee */
            code_insee: string;
            /** Nom */
            nom: string;
            /** Departement */
            departement?: string | null;
            /** Region */
            region?: string | null;
            /** Population */
            population?: number | null;
            couleur: components["schemas"]["CouleurSynthese"];
        };
        /**
         * CommuneProximite
         * @description Commune voisine d'un point géographique.
         */
        CommuneProximite: {
            /** Code Insee */
            code_insee: string;
            /** Nom */
            nom: string;
            /** Distance M */
            distance_m: number;
            /** Hex */
            hex: string;
        };
        /**
         * CommuneResultat
         * @description Élément d'autocomplétion / de recherche.
         *
         *     `hex` (couleur de synthèse) et `famille` (dominante) sont nuls pour une
         *     commune sans couleur calculée.
         */
        CommuneResultat: {
            /** Code Insee */
            code_insee: string;
            /** Nom */
            nom: string;
            /** Departement */
            departement?: string | null;
            /** Hex */
            hex?: string | null;
            /** Famille */
            famille?: string | null;
        };
        /**
         * CouleurScrutin
         * @description Couleur OKLCH d'un scrutin pour une commune.
         */
        CouleurScrutin: {
            /** L */
            l: number;
            /** C */
            c: number;
            /** H */
            h: number;
        };
        /**
         * CouleurSynthese
         * @description Couleur politique synthétique d'une commune.
         *
         *     `algo` = algo de dominance servi (cf. pipeline.couleur.ALGOS) ;
         *     `famille_dominante` en dépend — pour « tendance »/« blocs » elle peut
         *     différer de la première entrée de `repartition` (qui reste le classement
         *     complet, divers inclus, identique pour tous les algos).
         */
        CouleurSynthese: {
            /** Code Insee */
            code_insee: string;
            /** L */
            l: number;
            /** C */
            c: number;
            /** H */
            h: number;
            /** Hex */
            hex: string;
            /**
             * Algo
             * @default complet
             */
            algo: string;
            /** Famille Dominante */
            famille_dominante?: string | null;
            /** Participation Mediane */
            participation_mediane: number;
            /** Scrutins Inclus */
            scrutins_inclus: [
                string,
                number
            ][];
            /**
             * Repartition
             * @default []
             */
            repartition: components["schemas"]["FamilleSynthese"][];
        };
        /**
         * DetailScrutinResponse
         * @description Réponse de GET /communes/{insee}/scrutins/{scrutin_id}.
         */
        DetailScrutinResponse: {
            /** Insee */
            insee: string;
            /** Scrutin Id */
            scrutin_id: string;
            /** Familles */
            familles: components["schemas"]["FamilleVoix"][];
            /** Participation */
            participation: number;
            couleur: components["schemas"]["CouleurScrutin"];
        };
        /**
         * FamilleSynthese
         * @description Part synthétique (pondérée) d'une famille politique dans la couleur de la ville.
         */
        FamilleSynthese: {
            /** Famille */
            famille: string;
            /** Part */
            part: number;
        };
        /**
         * FamilleVoix
         * @description Voix d'une famille politique pour un scrutin.
         */
        FamilleVoix: {
            /** Famille */
            famille: string;
            /** Voix */
            voix: number;
            /** Pourcentage */
            pourcentage: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ListeScrutinsResponse
         * @description Réponse de GET /communes/{insee}/scrutins.
         */
        ListeScrutinsResponse: {
            /** Insee */
            insee: string;
            /** Scrutins */
            scrutins: components["schemas"]["ScrutinInclus"][];
        };
        /**
         * ScrutinInclus
         * @description Un scrutin inclus dans la synthèse de la commune.
         */
        ScrutinInclus: {
            /** Scrutin Id */
            scrutin_id: string;
            /** Type */
            type: string;
            /** Date */
            date: string;
            /** Poids Relatif */
            poids_relatif: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_communes_search_get: {
        parameters: {
            query: {
                /** @description Nom (ou partie du nom) de commune */
                q: string;
                limite?: number;
                algo?: "complet" | "tendance" | "blocs";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommuneResultat"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proximite_communes_proximite_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                rayon_m?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommuneProximite"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    couleur_communes__insee__couleur_get: {
        parameters: {
            query?: {
                algo?: "complet" | "tendance" | "blocs";
            };
            header?: never;
            path: {
                insee: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouleurSynthese"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fiche_communes__insee__get: {
        parameters: {
            query?: {
                algo?: "complet" | "tendance" | "blocs";
            };
            header?: never;
            path: {
                insee: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommuneFiche"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liste_scrutins_communes__insee__scrutins_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insee: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListeScrutinsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_scrutin_communes__insee__scrutins__scrutin_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insee: string;
                scrutin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailScrutinResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
